### ISSUE TITLE
Support Yomichan json dictionaries.

### ISSUE THREAD

**Issue by matsumurae** [cessen/kobo_jp_dict#1]
The idea is to have the same results I have with yomichan (I'm using JMNedict, JMDict, KireiCake, Shinmekai and Daijisen), I'm curious if it would be possible to combine multiple dictionaries into one and have the same on my Kobo.

Also not sure if i would be able to use them even as a separated dict, they're json not XML.

Never worked with dictionaries so sorry if this is a dumb question!

**Comment by cessen** [comment]
Hi @matsumurae!

Right now I've only written the code to support a specific set of dictionaries (two of which are included as gzipped files under `dictionaries/` in this repo).  You can indeed combine all three supported dictionaries into a single dictionary for Kobo.  Unfortunately, I haven't added support for Yomichan dictionaries yet.

But I think that's a great idea, and adding support for them is definitely possible.  I have some free time today, so I might take a first crack at it.

**Comment by cessen** [comment]
I'm working on this in the [yomichan_support](https://github.com/cessen/kobo_jp_dict/tree/yomichan_support) branch.

So far I have reading the dictionaries working.  Next step is to actually integrate that data into the generated the dictionary.

**Comment by cessen** [comment]
Just dropping a line to say that I do still plan to get around to this, but am currently a bit on the busy side, so it might be a while.  But I haven't abandoned this issue.

**Comment by cessen** [comment]
I've made a little more progress on this now.  If you compile the `yomichan_support` branch, you can now specify yomichan .zip files, and it will read them and (mostly) include them in the resulting dictionary.  A quick summary of the current state:

- Kanji dictionaries work great.  I'm currently using it for this, and made the entries reasonably nicely formatted.
- Word dictionaries get combined with the existing entries in a weird way.  So basically: *technically* usable, but the formatting is really abysmal, and kind of confusing.  But the entries are there.
- Name dictionaries aren't included yet, even though they're parsed.  I'll probably get this working next, since along with kanji it's the thing that's entirely missing from the existing dictionary.

I'll probably (no promises) be hacking on this over the course of this month, and hopefully get it all working nicely and merged into master.

**Comment by matsumurae** [comment]
Thanks for your hard work, really you're awesome!

Word entries are my main problem so maybe it's not so useful for me now haha I'll check it and see if I can help in any way

**Comment by cessen** [comment]
Oh, yeah, the word entries are *weird* right now.  I don't think it's worth testing yet.  I'll post another comment here once I've gotten that working properly.

**Comment by cessen** [comment]
Okay, I think the feature is basically ready, aside from some testing and bug fixing.  I opened a PR to track it here: #2

If you want to take a crack at using it, and let me know if you run into any issues, that would be awesome.  To add yomichan dictionaries you use the `-y` flag.  You need to repeat the flag for each included dictionary, but you can include as many as you like.  For example:

```
kobo_jp_dict output_dictionary.zip -j JMdict_e.xml -p accents.tsv -y kanjidic_english.zip -y 三省堂　スーパー大辞林.zip -y jmnedict.zip
```

**Comment by matsumurae** [comment]
Wow that was really fast! I'll check it out when I have some free time. I'll let you know if I see something wrong.

**Comment by cessen** [comment]
I've merged Yomichan dictionary support into master.  If you run into any issues with it please feel free to open another issue!
