### ISSUE TITLE
[Request] Remove English from Japanese-Japanese dictionary

### ISSUE THREAD

**Issue by brennier** [cessen/kobo_jp_dict#5]
Firstly, I want to say that this project is fantastic. I spent a lot of time trying to install custom Japanese dictionaries using other programs, but this one was the only one that worked flawlessly. Being able to use a well-known and comprehensive Japanese-Japanese dictionary like 大辞林 is a large improvement over the built-in Japanese-Japanese dictionary. Also a big thumbs up for using Rust!

I was wondering if I could request a command-line flag for not adding the English grammar tags to the dictionary entries (e.g. "verb, ichidan, intransitive" or "i-adjective, irregular"). That way, the Japanese-Japanese dictionary can be completely in Japanese.

**Comment by cessen** [comment]
Yeah, that should be super easy, actually.

I think these are the equivalents in Japanese:
- verb -> 動詞
- adjective -> 形容詞
- transitive -> 他動
- intransitive -> 自動
- irregular -> 変格 (?)
- ichidan -> 一段
- godan -> 五段

I'm not sure about 変格, but I can probably just leave that out when this flag is used.  If people are at the monolingual stage, they probably don't need irregularity indicated since all the irregular words are 1. few in number and 2. super common and they'd have learned them already.

**Comment by cessen** [comment]
Added in c3298760d3adef2268d3dfc673194e476ee2ac47.  Just pass the `-j` flag and it will use Japanese terms in entry headers instead of English.

**Comment by brennier** [comment]
Many thanks!

Honestly, I've been using Japanese-Japanese dictionaries for years now and never paid attention to how they marked the grammar. It seems that they usually use one kanji abbreviations. For example, shinmeikai use 形 for adjective, 自五 for an intransitive godan verb, 他下一 for a transitive ichidan verb that ends with a え段 kana before the る. I don't find any markings for "irregular", though. Irregular verbs such as 為る and 来る get their own categories marked with サ and カ respectively.

Anyway, I think your system is good! All these special markings used in Japanese dictionaries are kind of unnecessary due to how regular Japanese is.
